services:
  docs:
    image: local_lms_local_docs
    container_name: local_lms_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./local_lms:/app/local_lms:z
    ports:
      - '9000:9000'
    command: /start-docs
